vich_uploader:
    db_driver: orm

    mappings:
        user_object:
            uri_prefix: /images/users
            upload_destination: '%kernel.project_dir%/public/images/users'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
        publication_object:
                uri_prefix: /images/publications
                upload_destination: '%kernel.project_dir%/public/images/publications'
                namer: Vich\UploaderBundle\Naming\OrignameNamer

